# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'floods_selection.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FloodsSelection(object):
    def setupUi(self, FloodsSelection):
        FloodsSelection.setObjectName("FloodsSelection")
        FloodsSelection.resize(1000, 600)
        FloodsSelection.setMinimumSize(QtCore.QSize(1000, 600))
        FloodsSelection.setMaximumSize(QtCore.QSize(1000, 600))
        self.options_frame = QtWidgets.QFrame(FloodsSelection)
        self.options_frame.setGeometry(QtCore.QRect(11, 11, 291, 578))
        self.options_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.options_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.options_frame.setObjectName("options_frame")
        self.location_frame = QtWidgets.QFrame(self.options_frame)
        self.location_frame.setGeometry(QtCore.QRect(10, 20, 271, 121))
        self.location_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.location_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.location_frame.setObjectName("location_frame")
        self.location_title_label = QtWidgets.QLabel(self.location_frame)
        self.location_title_label.setGeometry(QtCore.QRect(10, 0, 71, 16))
        self.location_title_label.setStyleSheet("font-size: 10pt;")
        self.location_title_label.setObjectName("location_title_label")
        self.region_label = QtWidgets.QLabel(self.location_frame)
        self.region_label.setGeometry(QtCore.QRect(10, 20, 131, 16))
        self.region_label.setStyleSheet("font-size: 8pt;\n"
"font-style: italic;")
        self.region_label.setObjectName("region_label")
        self.region_combobox = QtWidgets.QComboBox(self.location_frame)
        self.region_combobox.setGeometry(QtCore.QRect(10, 40, 251, 22))
        self.region_combobox.setObjectName("region_combobox")
        self.cityprovince_label = QtWidgets.QLabel(self.location_frame)
        self.cityprovince_label.setGeometry(QtCore.QRect(10, 70, 131, 16))
        self.cityprovince_label.setStyleSheet("font-size: 8pt;\n"
"font-style: italic;")
        self.cityprovince_label.setObjectName("cityprovince_label")
        self.location_combobox = QtWidgets.QComboBox(self.location_frame)
        self.location_combobox.setGeometry(QtCore.QRect(10, 90, 251, 22))
        self.location_combobox.setObjectName("location_combobox")
        self.date_frame = QtWidgets.QFrame(self.options_frame)
        self.date_frame.setGeometry(QtCore.QRect(10, 150, 271, 71))
        self.date_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.date_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.date_frame.setObjectName("date_frame")
        self.date_label = QtWidgets.QLabel(self.date_frame)
        self.date_label.setGeometry(QtCore.QRect(10, 0, 71, 16))
        self.date_label.setStyleSheet("font-size: 10pt;")
        self.date_label.setObjectName("date_label")
        self.date_description_label = QtWidgets.QLabel(self.date_frame)
        self.date_description_label.setGeometry(QtCore.QRect(10, 20, 131, 16))
        self.date_description_label.setStyleSheet("font-size: 8pt;\n"
"font-style: italic;")
        self.date_description_label.setObjectName("date_description_label")
        self.date_combobox = QtWidgets.QComboBox(self.date_frame)
        self.date_combobox.setGeometry(QtCore.QRect(10, 40, 251, 22))
        self.date_combobox.setObjectName("date_combobox")
        self.search_button = QtWidgets.QPushButton(self.options_frame)
        self.search_button.setGeometry(QtCore.QRect(70, 240, 141, 28))
        self.search_button.setObjectName("search_button")
        self.cancel_button = QtWidgets.QPushButton(self.options_frame)
        self.cancel_button.setGeometry(QtCore.QRect(70, 540, 151, 28))
        self.cancel_button.setObjectName("cancel_button")
        self.frame = QtWidgets.QFrame(self.options_frame)
        self.frame.setGeometry(QtCore.QRect(10, 290, 271, 191))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.status_label = QtWidgets.QLabel(self.frame)
        self.status_label.setGeometry(QtCore.QRect(10, 10, 71, 16))
        self.status_label.setStyleSheet("font-size: 10pt;")
        self.status_label.setObjectName("status_label")
        self.status_description_label = QtWidgets.QLabel(self.frame)
        self.status_description_label.setGeometry(QtCore.QRect(10, 30, 251, 16))
        self.status_description_label.setStyleSheet("font-size: 8pt;\n"
"font-style: italic;")
        self.status_description_label.setText("")
        self.status_description_label.setObjectName("status_description_label")
        self.selection_frame = QtWidgets.QFrame(FloodsSelection)
        self.selection_frame.setGeometry(QtCore.QRect(308, 11, 681, 578))
        self.selection_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.selection_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.selection_frame.setObjectName("selection_frame")

        self.retranslateUi(FloodsSelection)
        QtCore.QMetaObject.connectSlotsByName(FloodsSelection)

    def retranslateUi(self, FloodsSelection):
        _translate = QtCore.QCoreApplication.translate
        FloodsSelection.setWindowTitle(_translate("FloodsSelection", "Floods | Select Data"))
        self.location_title_label.setText(_translate("FloodsSelection", "Location"))
        self.region_label.setText(_translate("FloodsSelection", "Region"))
        self.cityprovince_label.setText(_translate("FloodsSelection", "City/Province"))
        self.date_label.setText(_translate("FloodsSelection", "Date"))
        self.date_description_label.setText(_translate("FloodsSelection", "Description"))
        self.search_button.setText(_translate("FloodsSelection", "Search Data"))
        self.cancel_button.setText(_translate("FloodsSelection", "Cancel"))
        self.status_label.setText(_translate("FloodsSelection", "Status"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FloodsSelection = QtWidgets.QWidget()
    ui = Ui_FloodsSelection()
    ui.setupUi(FloodsSelection)
    FloodsSelection.show()
    sys.exit(app.exec_())
