# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'floods_home.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FloodsHome(object):
    def setupUi(self, FloodsHome):
        FloodsHome.setObjectName("FloodsHome")
        FloodsHome.resize(800, 500)
        FloodsHome.setMinimumSize(QtCore.QSize(800, 500))
        FloodsHome.setMaximumSize(QtCore.QSize(800, 500))
        self.horizontalLayout = QtWidgets.QHBoxLayout(FloodsHome)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.floods_info_frame = QtWidgets.QFrame(FloodsHome)
        self.floods_info_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.floods_info_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.floods_info_frame.setObjectName("floods_info_frame")
        self.floods_picture_label = QtWidgets.QLabel(self.floods_info_frame)
        self.floods_picture_label.setGeometry(QtCore.QRect(20, 20, 351, 291))
        self.floods_picture_label.setObjectName("floods_picture_label")
        self.floods_info_label = QtWidgets.QLabel(self.floods_info_frame)
        self.floods_info_label.setGeometry(QtCore.QRect(30, 370, 331, 81))
        self.floods_info_label.setObjectName("floods_info_label")
        self.horizontalLayout.addWidget(self.floods_info_frame)
        self.floods_selection_frame = QtWidgets.QFrame(FloodsHome)
        self.floods_selection_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.floods_selection_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.floods_selection_frame.setObjectName("floods_selection_frame")
        self.button_frame = QtWidgets.QFrame(self.floods_selection_frame)
        self.button_frame.setGeometry(QtCore.QRect(40, 250, 301, 181))
        self.button_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.button_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.button_frame.setObjectName("button_frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.button_frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.view_button = QtWidgets.QPushButton(self.button_frame)
        self.view_button.setObjectName("view_button")
        self.verticalLayout.addWidget(self.view_button)
        self.create_button = QtWidgets.QPushButton(self.button_frame)
        self.create_button.setObjectName("create_button")
        self.verticalLayout.addWidget(self.create_button)
        self.quit_button = QtWidgets.QPushButton(self.button_frame)
        self.quit_button.setObjectName("quit_button")
        self.verticalLayout.addWidget(self.quit_button)
        self.horizontalLayout.addWidget(self.floods_selection_frame)

        self.retranslateUi(FloodsHome)
        QtCore.QMetaObject.connectSlotsByName(FloodsHome)

    def retranslateUi(self, FloodsHome):
        _translate = QtCore.QCoreApplication.translate
        FloodsHome.setWindowTitle(_translate("FloodsHome", "floods"))
        self.floods_picture_label.setText(_translate("FloodsHome", "Insert Picture Here"))
        self.floods_info_label.setText(_translate("FloodsHome", "Insert Information Here"))
        self.view_button.setText(_translate("FloodsHome", "View Existing Data"))
        self.create_button.setText(_translate("FloodsHome", "Create New Data"))
        self.quit_button.setText(_translate("FloodsHome", "Quit Application"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FloodsHome = QtWidgets.QWidget()
    ui = Ui_FloodsHome()
    ui.setupUi(FloodsHome)
    FloodsHome.show()
    sys.exit(app.exec_())
